// Bilingual strings for Больничная аптека / Hospital Pharmacy
export const LANG_CONST = {
  ru: {
    // App
    appName: "Больничная аптека. Стационар",
    appHint: "Информационная система учёта лекарственных средств",
    // Login
    signIn: "Вход в систему",
    signInHint: "Выберите роль и введите учётные данные",
    role: "Роль",
    login: "Логин",
    password: "Пароль",
    loginPh: "Введите логин",
    pwdPh: "Введите пароль",
    remember: "Запомнить на этом устройстве",
    forgot: "Забыли пароль?",
    submit: "Войти",
    or: "или",
    sso: "Войти через ЕСИА",
    needHelp: "Проблемы со входом?",
    contactAdmin: "Обратитесь к администратору",
    // Roles
    roleAdmin: "Администратор",
    roleAdminDesc: "Полный доступ к системе и настройкам",
    roleAdminGlyph: "А",
    rolePharm: "Фармацевт",
    rolePharmDesc: "Каталог, поступления, выдача, списания",
    rolePharmGlyph: "Ф",
    roleNurse: "Медсестра",
    roleNurseDesc: "Заявки от отделения, получение препаратов",
    roleNurseGlyph: "М",
    // Main screen
    inventory: "Каталог препаратов",
    inventoryHint: "Учёт остатков и сроков годности",
    search: "Поиск по наименованию, МНН, штрих-коду…",
    filters: "Фильтры",
    addItem: "Добавить препарат",
    export: "Экспорт",
    all: "Все",
    lowStock: "Заканчивается",
    expiring: "Истекает срок",
    narcotic: "НС и ПВ",
    // Table headers
    name: "Наименование",
    inn: "МНН",
    form: "Форма",
    batch: "Серия",
    stock: "Остаток",
    expiry: "Срок годности",
    location: "Место хранения",
    status: "Статус",
    // Sidebar
    nav_dashboard: "Сводка",
    nav_inventory: "Каталог",
    nav_requisitions: "Заявки",
    nav_receipts: "Поступления",
    nav_writeoffs: "Списания",
    nav_narcotic: "НС и ПВ",
    nav_reports: "Отчёты",
    nav_settings: "Настройки",
    // Filters
    fGroup: "Фармакологическая группа",
    fForm: "Лекарственная форма",
    fLoc: "Место хранения",
    fStatus: "Статус",
    reset: "Сбросить",
    apply: "Применить",
    any: "Любая",
    // Statuses
    sNormal: "В наличии",
    sLow: "Мало",
    sExp: "Истекает",
    sCrit: "Критично",
    // Stat cards
    totalItems: "Позиций в каталоге",
    lowItems: "Заканчивается",
    expiringItems: "Истекает в 30 дней",
    valueItems: "Стоимость остатков",
    // Misc
    units: "уп.",
    pcs: "шт.",
    days: "дн.",
    showing: "Показано",
    of: "из",
    page: "Страница",
    logout: "Выйти",
    profile: "Профиль",
    notifications: "Уведомления",
    today: "Сегодня",
    sections: {
      users:        "Пользователи",
      storages:     "Склады",
      medications:  "База лекарств",
      requests:     "Запросы",
      reports:      "Отчёты",
      mainStorage:  "Основной склад",
      deptStorages: "Склады отделений",
      myRequests:   "Мои запросы",
    },
    // Table column headers — keyed by raw API field name.
    fields: {
      username:          "Логин",
      name:              "Наименование",
      middlename:           "Фамилия",
      lastname:          "Отчество",
      role:              "Роль",
      linkedStorageId:   "Склад",
      description:       "Описание",
      isRequiredRecipe:  "Рецептурный",
      manufacturer:      "Производитель",
      countryName:       "Страна",
      isPharmacyStorage: "Хранит лекарства",
      number:            "№",
      creatorName:       "Создатель",
      handlerName:       "Обработчик",
      status:            "Статус",
      creationDate:      "Дата создания",
      productName:       "Препарат",
      productCount:      "Кол-во",
      productType:       "Тип продукта",
      countryOfOriginId: "Страна (id)",
      creatorId:         "Создатель (id)",
      creationDateFrom:  "Создан с",
      creationDateTo:    "Создан по",
      password:          "Пароль",
      countryId:         "Страна",
      sourceBatchId:     "Партия источника",
      targetBatchId:     "Партия назначения",
      targetStorageId:   "Склад назначения",
      count:             "Количество",
    },
    // Common backend enum / boolean values.
    values: {
      true:           "Да",
      false:          "Нет",
      ROLE_ADMIN:     "Администратор",
      ROLE_PHARMACIST:"Фармацевт",
      ROLE_NURSE:     "Медсестра",
      // product types
      TABLETS:        "Таблетки",
      POWDER:         "Порошок",
      GRANULES:       "Гранулы",
      CAPSULES:       "Капсулы",
      PILLS:          "Пилюли",
      OINTMENT:       "Мазь",
      GEL:            "Гель",
      SUPPOSITORIES:  "Свечи",
      PLASTER:        "Пластырь",
      SYRUP:          "Сироп",
      SOLUTION:       "Раствор",
      DROPS:          "Капли",
      MIXTURE:        "Микстура",
      EXTRACT:        "Экстракт",
      AEROSOL:        "Аэрозоль",
      SPRAY:          "Спрей",
    },
    loading: "Загрузка…",
    noData:  "Нет данных",
    cancel:  "Отмена",
    save:    "Сохранить",
    add:     "Добавить",
    edit:    "Редактировать",
  },
  en: {
    appName: "Hospital Pharmacy",
    appHint: "Medication accounting and inventory system",
    signIn: "Sign in",
    signInHint: "Choose your role and enter credentials",
    role: "Role",
    login: "Login",
    password: "Password",
    loginPh: "j.smith",
    pwdPh: "Enter password",
    remember: "Remember on this device",
    forgot: "Forgot password?",
    submit: "Sign in",
    or: "or",
    sso: "Sign in with SSO",
    needHelp: "Trouble signing in?",
    contactAdmin: "Contact your administrator",
    roleAdmin: "Administrator",
    roleAdminDesc: "Full system and configuration access",
    rolePharm: "Pharmacist",
    rolePharmDesc: "Catalog, receipts, dispensing, write-offs",
    roleNurse: "Nurse",
    roleNurseDesc: "Department requisitions and pickups",
    inventory: "Drug catalog",
    inventoryHint: "Stock levels and expiry tracking",
    search: "Search by name, INN, barcode…",
    filters: "Filters",
    addItem: "Add item",
    export: "Export",
    all: "All",
    lowStock: "Low stock",
    expiring: "Expiring",
    narcotic: "Controlled",
    name: "Name",
    inn: "INN",
    form: "Form",
    batch: "Batch",
    stock: "Stock",
    expiry: "Expiry",
    location: "Location",
    status: "Status",
    nav_dashboard: "Overview",
    nav_inventory: "Catalog",
    nav_requisitions: "Requisitions",
    nav_receipts: "Receipts",
    nav_writeoffs: "Write-offs",
    nav_narcotic: "Controlled",
    nav_reports: "Reports",
    nav_settings: "Settings",
    fGroup: "Pharmacological group",
    fForm: "Dosage form",
    fLoc: "Storage location",
    fStatus: "Status",
    reset: "Reset",
    apply: "Apply",
    any: "Any",
    sNormal: "In stock",
    sLow: "Low",
    sExp: "Expiring",
    sCrit: "Critical",
    totalItems: "Catalog items",
    lowItems: "Running low",
    expiringItems: "Expiring in 30 days",
    valueItems: "Stock value",
    units: "pkg",
    pcs: "pcs",
    days: "d",
    showing: "Showing",
    of: "of",
    page: "Page",
    logout: "Sign out",
    profile: "Profile",
    notifications: "Notifications",
    today: "Today",
  },
};